services:
  kidzgo.api:
    image: kidzgo.api
    build:
      context: .
      dockerfile: Kidzgo.API/Dockerfile
    ports:
      - "5152:8080"
      - "7165:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Database=Host=postgres;Port=5432;Database=kidzgo;Username=postgres;Password=1234;Include Error Detail=true
    depends_on:
      - postgres
    restart: unless-stopped
  
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: kidzgo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8081:80"

volumes:
  pgdata:
  qdrant_data:
